<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="Ass_Pallet" Id="{07db0394-8679-47b5-a6db-93ce50ed8062}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Ass_Pallet
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Ass_Pallet">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>